certmanager-issuer:
  email: adeleminian@gmail.com 

global:
  edition: ce
  hosts:
    domain: localhost
    host: localhost
    externalIP: 127.0.0.1
    https: false
    httpPort: 8080
    httpsPort: 8443

  ingress:
    configureCertmanager: true
    enabled: false
  externalUrl: http://localhost:8080
  railsSecrets:
    secretKeyBase: "a-very-secret-key-that-is-at-least-30-characters-long"

  appConfig:
    omniauth:
      allowSingleSignOn: ['gitlab']
    initialDefaults:
      signup_enabled: true

gitlab:
  webservice:
    ingress:
      tls:
        enabled: false
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
        
gitlab:
  workhorse:
    enabled: true
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

postgresql:
  install: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

redis:
  install: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
