Vagrant.configure("2") do |config|
  BOX_IMAGE = "ubuntu/jammy64"
  K3S_VERSION = "v1.32.5+k3s1"
  SERVER_IP = "192.168.56.110"

  config.vm.define "aeminianS" do |server|
    server.vm.box = BOX_IMAGE
    server.vm.hostname = "aeminianS"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.synced_folder ".", "/vagrant"

    server.vm.provision "shell", inline: <<-SHELL
      sudo ufw disable
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip #{SERVER_IP} --advertise-address #{SERVER_IP}" sh -
      echo "#{SERVER_IP} app1.com app2.com app3.com" | sudo tee -a /etc/hosts
      sleep 20
      sudo k3s kubectl apply -f /vagrant/app1/deploy.yaml
      sudo k3s kubectl apply -f /vagrant/app2/deploy.yaml
      sudo k3s kubectl apply -f /vagrant/app3/deploy.yaml
      sudo k3s kubectl apply -f /vagrant/ingress.yaml
    SHELL
  end
end
