global:
  hosts:
    domain: local.gitlab
    externalIP: "127.0.0.1"
  ingress:
    configureCertmanager: false
    tls:
      enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: true
