apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html2
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: app2
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html2
data:
  index.html: |
    <html>
    <head>
      <title>App 2</title>
    </head>
    <body>
      <h1>Welcome to App 2</h1>
      <p>This is the second application.</p>
    </body>
    </html>
---